version: '3.8'
services:
  api:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - TOKEN_QUANTITY=10
      - TOKEN_ALIVE_HOURS=4
      - REFRESH_TOKEN_ALIVE_HOURS=168
      - SECRET=supersecretkey
      - ALGORITHM=HS256 